version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    links:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'somethng'
      MYSQL_USER: 'me'
      MYSQL_PASSWORD: 'something'
      MYSQL_DATABASE: 'my_db'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3366:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql
volumes:
  mysqldata: {}